/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.demo.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TestEvent1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7378547066895566874L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TestEvent1\",\"namespace\":\"com.example.demo.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"random\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TestEvent1> ENCODER =
      new BinaryMessageEncoder<TestEvent1>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TestEvent1> DECODER =
      new BinaryMessageDecoder<TestEvent1>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TestEvent1> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TestEvent1> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TestEvent1>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TestEvent1 to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TestEvent1 from a ByteBuffer. */
  public static TestEvent1 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence value;
  @Deprecated public int random;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TestEvent1() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param value The new value for value
   * @param random The new value for random
   */
  public TestEvent1(java.lang.CharSequence id, java.lang.CharSequence value, java.lang.Integer random) {
    this.id = id;
    this.value = value;
    this.random = random;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return value;
    case 2: return random;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: value = (java.lang.CharSequence)value$; break;
    case 2: random = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'random' field.
   * @return The value of the 'random' field.
   */
  public java.lang.Integer getRandom() {
    return random;
  }

  /**
   * Sets the value of the 'random' field.
   * @param value the value to set.
   */
  public void setRandom(java.lang.Integer value) {
    this.random = value;
  }

  /**
   * Creates a new TestEvent1 RecordBuilder.
   * @return A new TestEvent1 RecordBuilder
   */
  public static com.example.demo.schema.TestEvent1.Builder newBuilder() {
    return new com.example.demo.schema.TestEvent1.Builder();
  }

  /**
   * Creates a new TestEvent1 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TestEvent1 RecordBuilder
   */
  public static com.example.demo.schema.TestEvent1.Builder newBuilder(com.example.demo.schema.TestEvent1.Builder other) {
    return new com.example.demo.schema.TestEvent1.Builder(other);
  }

  /**
   * Creates a new TestEvent1 RecordBuilder by copying an existing TestEvent1 instance.
   * @param other The existing instance to copy.
   * @return A new TestEvent1 RecordBuilder
   */
  public static com.example.demo.schema.TestEvent1.Builder newBuilder(com.example.demo.schema.TestEvent1 other) {
    return new com.example.demo.schema.TestEvent1.Builder(other);
  }

  /**
   * RecordBuilder for TestEvent1 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TestEvent1>
    implements org.apache.avro.data.RecordBuilder<TestEvent1> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence value;
    private int random;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.demo.schema.TestEvent1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.random)) {
        this.random = data().deepCopy(fields()[2].schema(), other.random);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TestEvent1 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.demo.schema.TestEvent1 other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.random)) {
        this.random = data().deepCopy(fields()[2].schema(), other.random);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.demo.schema.TestEvent1.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.demo.schema.TestEvent1.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.example.demo.schema.TestEvent1.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.example.demo.schema.TestEvent1.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'random' field.
      * @return The value.
      */
    public java.lang.Integer getRandom() {
      return random;
    }

    /**
      * Sets the value of the 'random' field.
      * @param value The value of 'random'.
      * @return This builder.
      */
    public com.example.demo.schema.TestEvent1.Builder setRandom(int value) {
      validate(fields()[2], value);
      this.random = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'random' field has been set.
      * @return True if the 'random' field has been set, false otherwise.
      */
    public boolean hasRandom() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'random' field.
      * @return This builder.
      */
    public com.example.demo.schema.TestEvent1.Builder clearRandom() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TestEvent1 build() {
      try {
        TestEvent1 record = new TestEvent1();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.random = fieldSetFlags()[2] ? this.random : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TestEvent1>
    WRITER$ = (org.apache.avro.io.DatumWriter<TestEvent1>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TestEvent1>
    READER$ = (org.apache.avro.io.DatumReader<TestEvent1>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
