spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      specific.avro.reader: true
    consumer:
      auto-offset-reset: earliest
      group-id: baeldung
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: com.example.demo.CustomKafkaAvroDeserializer
      properties:
        spring.json.trusted.packages: com.example.demo
        schema.registry.url: not-used
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: com.example.demo.CustomKafkaAvroSerializer
      auto.register.schemas: true
      properties:
        schema.registry.url: not-used
test:
  topic: embedded-test-topic
  topic-pojo: embedded-test-topic-pojo
  topic-avro: embedded-test-topic-avro
