spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      auto.register.schemas: false
      use.latest.version: true
    consumer:
      auto-offset-reset: earliest
      group-id: baeldung
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.json.trusted.packages: com.example.demo
        schema.registry.url: http://mock:3000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://mock:3000
        specific.avro.reader: true
        auto.register.schemas: false
        use.latest.version: true
test:
  topic: embedded-test-topic
  topic-pojo: embedded-test-topic-pojo
  topic-avro: embedded-test-topic-avro
